version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network
      
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - my-network
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - mongo  

networks:
  my-network:
    driver: bridge